const os = require("os");
console.log(os.availableParallelism());
console.log(os.arch());
console.log(os.cpus());
console.log(os.freemem());
console.log(os.homedir());
console.log(os.hostname());
console.log(os.machine());
console.log(os.release());
console.log(os.tmpdir());
console.log(os.version());
